max_steps = 20

[model]
name = "Qwen/Qwen3-4b"

[orchestrator]
batch_size = 48
rollouts_per_example = 16
seq_len = 2048

[orchestrator.sampling]
max_tokens = 6000

[[orchestrator.env]]
id = "omit_description"

[trainer.optim]
lr = 3e-6
